deploymentConfig:
  # The organisation name of your deployment repo
  org: baloise-incubator
  # The repostiory name of your deployment repo
  repository: okd4-example-apps
  # The name of the application that is used in your deployment repo
  applicationName: gitops-nginx-demo

previewConfig:
  network:
    http:
      ingress:
        host:
          # your router host.
          #{SHA256_8CHAR_BRANCH_HASH} gets replaced by a shortened hash of your feature branch name
          template: gitops-nginx-demo-{SHA256_8CHAR_BRANCH_HASH}.apps.okd.baloise.dev
  replace:
    # Paths that should be replaced
    - path: gitops-demo.image.tag
      variable: GIT_COMMIT # this is the latest git hash of the PR branch
    - path: network.http.ingress.host
      variable: ROUTE_HOST # this is the resolved SHA256_8CHAR_BRANCH_HASH from above
