apiVersion: v2
applicationname: kargo-demo-nginx-demo
previewConfig:
  host: ${PREVIEW_NAMESPACE}.apps.baloise.dev
  target:
    organisation: baloise-incubator
    repository: okd4-example-apps
  replace:
    Chart.yaml:
      - path: name
        value: ${PREVIEW_NAMESPACE}
    values.yaml:
      - path: gitops-demo.image.tag
        value: ${GIT_HASH}
      - path: gitops-demo.network.http.ingress.host
        value: ${PREVIEW_HOST}