deploymentConfig:
  # The organisation name of your deployment repo
  org: baloise-incubator
  # The repostiory name of your deployment repo
  repository: deployments
  # The name of the application that is used in your deployment repo
  applicationName: gitops-nginx-demo

previewConfig:
  route:
    host:
      # your router host.
      #{SHA256_8CHAR_BRANCH_HASH} gets replaced by a shortened hash of your feature branch name
      template: example-{SHA256_8CHAR_BRANCH_HASH}.apps.origin.baloise.dev
  replace:
    # Paths that should be replaced
    - path: image.tag
      variable: GIT_COMMIT # this is the latest git hash of the PR branch
    - path: route.host
      variable: ROUTE_HOST # this is the resolved SHA256_8CHAR_BRANCH_HASH from above
