apiVersion: v2_beta
applicationName: gitops-nginx-demo
previewConfig:
  host: "${APPLICATION_NAME}-${PREVIEW_ID}-${PREVIEW_ID_HASH_SHORT}-preview.apps.baloise.dev"
  target:
    organisation: baloise-incubator
    repository: okd4-example-apps
    namespace: "${APPLICATION_NAME}-${PREVIEW_ID_HASH_SHORT}-preview"
  replace:
    Chart.yaml:
      - path: name
        value: "${PREVIEW_NAMESPACE}"
    values.yaml:
      - path: gitops-demo.image.tag
        value: "${GIT_HASH}"
      - path: gitops-demo.network.http.ingress.host
        value: "${PREVIEW_HOST}"