apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: gitops-nginx-demo-pipeline
spec:
  serviceAccountName: harbor-sa
  pipelineRef:
    name: build-and-push
  resources:
    - name: repo
      resourceRef:
        name: demo-git-resource
    - name: image
      resourceRef:
        name: demo-image-resource
