apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-push
spec:
  resources:
    - name: repo
      type: git
    - name: image
      type: image

  tasks:
    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      resources:
        inputs:
          - name: source
            resource: repo
        outputs:
          - name: image
            resource: image
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: gitops-nginx-demo-pipeline
spec:
  serviceAccountName: harbor-sa
  pipelineRef:
    name: build-and-push
  resources:
    - name: repo
      resourceRef:
        name: gitops-example-static-git-resource
    - name: image
      resourceRef:
        name: gitops-example-static-image-resource
