kargo-joachim-chart:
  replicaCount: 1
  image:
    repository: docker.io/niiku/gitops-nginx-demo
    tag: REPLACEME_CHANGED
  network:
    http:
      servicePort: 8080
      ingress:
        host: REPLACEME
  readinessProbe:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 15
    timeoutSeconds: 1
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 1
      memory: 32Mi
