name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ vars.DOCKER_USER }}/gitops-nginx-demo

jobs:
  container-build-push:
    name: Build container image and push if release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  helm-push:
    name: Push Helm Chart
    needs: container-build-push
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v') }}
    permissions:
      contents: write
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install helm & yq tools
        uses: yokawasa/action-setup-kube-tools@v0.9.3
        with:
          setup-tools: |
            helmv3
            yq
          helm: "3.13.1"
          yq: "4.35.2"
      - name: Configure Git
        run: |
          git config user.name "Incubator"
          git config user.email "incubator@users.noreply.github.com"
      - name: Set image tag in Chart
        run: |
          yq e -i ".app.image.tag = \"${{github.ref_name}}\"" charts/gitops-nginx-demo/values.yaml
      - name: Create commit
        id: create-commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: charts/**
          commit_message: "Update chart version"

      - name: Save commit hash
        id: save-commit-hash
        run: |
          if [ "${{ steps.create-commit.outputs.changes_detected || 'unknown' }}" == "true" ]; then
            echo "commit_hash=${{ steps.create-commit.outputs.commit_hash }}" >> "$GITHUB_OUTPUT"
          else
            echo "commit_hash=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.save-commit-hash.outputs.commit_hash }}
          fetch-depth: 0
      - name: Checkout forked chart-releaser
        uses: actions/checkout@v3
        with:
          repository: edmondop/chart-releaser-action
          path: chart-releaser-action
          ref: ef58c21b3f93daff872ba384abd9cdb16e715334
      - name: Run chart-releaser
        uses: ./chart-releaser-action
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"

  reload-warehouse:
    name: Refresh kargo warehouse
    needs: helm-push
    if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Reload warehouse
        uses: actions-hub/kubectl@master
        env:
          KUBE_HOST: ${{ secrets.KUBE_HOST }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
        with:
          args: annotate warehouse kargo-demo -n kargo-demo-stages reload=${{ github.sha }} --overwrite
      - name: Reload warehouse2
        uses: actions-hub/kubectl@master
        env:
          KUBE_HOST: ${{ secrets.KUBE_HOST }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
        with:
          args: annotate warehouse kargo-joachim -n kargo-joachim-stages reload=${{ github.sha }} --overwrite